// pizzas_frontend_react_state/src/components/Navbar.js
import { Link } from 'react-router-dom';

function Navbar() {
  return (
    <div className="navbar">
      <div className="navbar__inner">
        <div className="container">
          <div className="navbar__heading">
            <Link to="/">PizzaHaus</Link>
            <span className="heading__sub">"Our dough, your pizza"</span>
          </div>
          <ul className="navbar__navigation">
            <li></li>
          </ul>
        </div>
      </div>
    </div>
  );
}

export default Navbar;

// plants_direct_vue/cli/src/src/components/Navbar.vue
<template>
  <div class="navbar" data-cy="navbar">
    <div class="navbar__inner">
      <div class="container">
        <div class="navbar__heading">
          <router-link to="/">
            Plants Direct
            <span class="heading__sub">"Our plants, your passion"</span>
          </router-link>
        </div>
        <ul class="navbar__navigation" data-cy="navbar--home">
          <li>
            <router-link to="/" data-cy="navbar--link">
              Home
            </router-link>
          </li>
          <li>
            <router-link to="/about" data-cy="navbar--link">About</router-link>
          </li>
          <li>
            <router-link to="/contact" data-cy="navbar--link">
              Contact
            </router-link>
          </li>
        </ul>
        <div class="navbar__cart">
          Cart ({{ $store.getters.getCartLength }})
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  export default {
    name: 'Navbar',
  };
</script>
