// plants_direct_vue/cli/src/src/components/Product.vue
<template>
  <div class="product" data-cy="product">
    <h3>{{ product.name }}</h3>
    <img
      v-bind:src="getImageSrc(product)"
      v-bind:title="getImageTitle(product)"
    />
    <p>
      {{ product.description }}
    </p>
    <ul v-for="feature in product.features" v-bind:key="feature">
      <li>{{ feature }}</li>
    </ul>
    <p>&pound;{{ product.price }}</p>
    <p v-if="product.stockLevel === 0">Out of stock :(</p>
    <div class="promo-blocks__actions">
      <router-link
        v-bind:to="{
          name: 'productDetails',
          params: { productId: product.productId },
        }"
        v-on:add-to-cart="addToCart"
        class="anchor--button"
        data-cy="product--link"
      >
        Full Details
      </router-link>
      <button
        v-on:click="addToCart(product)"
        v-if="product.stockLevel > 0"
        data-cy="product--addToCart"
      >
        {{ product.addedToCart ? 'Remove from cart' : 'Add to cart' }}
      </button>
    </div>
  </div>
</template>

<script>
  export default {
    name: 'Product',
    props: ['product'],
    methods: {
      addToCart(product) {
        product.addedToCart = !product.addedToCart;
        this.$store.commit('updateCart', product.productId);
      },
      getImageSrc(product) {
        return product.images[0].imageSrc;
      },
      getImageTitle(product) {
        return product.images[0].title;
      },
    },
  };
</script>

// pizzas_frontend_react_state/src/components/Product.js
import { Link } from 'react-router-dom';

function Product(props) {
  const editUrl = '/products/' + props.product.id + '/edit';

  /**
   * Handle deletion of product
   * @param {*} event
   *
   */
  async function handleDelete(event) {
    props.deleteProduct(event.target.getAttribute('data-productid'));
  }

  return (
    <div className="product">
      <h3>{props.product.name} </h3>
      <img src={props.product.image} alt={props.product.name} />

      <p>&pound;{props.product.price}</p>
      <div className="promo-blocks__actions">
        <Link to={editUrl} className="anchor--button">
          Edit
        </Link>
        <button data-productid={props.product.id} onClick={handleDelete}>
          Delete
        </button>
      </div>
    </div>
  );
}

export default Product;
